import { useEffect, useState } from 'react'
import { api, post } from './api'
import { communityModule } from './modules'
type Link={module_id:string;user_id:string;github_login:string;revoked:number;created_at:string}
export function MaintainerAccess(){
  const [items,setItems]=useState<Link[]>([]),[error,setError]=useState(''),[selected,setSelected]=useState<Link|null>(null),[note,setNote]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{let cancelled=false;void api<Link[]>('/admin/maintainers').then(value=>{if(!cancelled)setItems(value)}).catch(error=>{if(!cancelled)setError(error.message)});return()=>{cancelled=true}},[])
  async function save(){if(!selected)return;setBusy(true);setError('');try{await post('/admin/maintainers/'+selected.module_id+'/'+selected.user_id,{note},selected.revoked?'PATCH':'DELETE');setItems(await api<Link[]>('/admin/maintainers'));setSelected(null);setNote('')}catch(error){setError(error instanceof Error?error.message:'Unable to change maintainer access.')}finally{setBusy(false)}}
  return <section className="configuration-section"><h2>Developer module access</h2><p className="service-note">Developers sign in through GitHub and claim modules that declare their handle. Revoking access blocks new claims and private reports until restored here. Source maintainer changes still require a reviewed PR.</p>{items.map(item=><article className="inbox-issue" key={item.module_id+item.user_id}><div className="section-title"><strong>{communityModule(item.module_id)?.name??item.module_id} · @{item.github_login}</strong><span className="pill">{item.revoked?'Revoked':'Active'}</span></div><small>{item.module_id}</small><button className="text-button" onClick={()=>{setSelected(item);setNote('')}}>{item.revoked?'Restore access':'Revoke access'}</button></article>)}{!items.length&&!error&&<p className="service-note">No modules have been claimed yet.</p>}{selected&&<form className="community-form" onSubmit={event=>{event.preventDefault();void save()}}><label>Reason<input value={note} onChange={event=>setNote(event.target.value)} required maxLength={1000}/></label><div className="forum-actions"><button className="button button-primary" disabled={busy||!note.trim()}>{selected.revoked?'Restore access':'Revoke access'}</button><button type="button" className="button button-quiet" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button></div></form>}{error&&<p className="file-error" role="alert">{error}</p>}</section>
}
