import { cleanupPush, startPush } from './server/push'
import { cleanupDeveloperAuth } from './server/developer-auth'
import { cleanupAccounts } from './server/accounts'
import { cleanupUsage } from './server/usage'
import { ensureModuleThreads } from './server/module-threads'
import { sendActivityDigests } from './server/activity-mail'
import { cleanupForumMedia } from './server/forum-media'
import { handleCommunity } from './server/transport'
import type { Env } from './server/platform'
export default { fetch(request: Request, env: Env, context?: {waitUntil(promise: Promise<unknown>): void}) { return handleCommunity(request, env, context) }, scheduled(event: {cron?: string}, env: Env, context: {waitUntil(promise: Promise<unknown>): void}) { if(event.cron==='* * * * *'){startPush(env,context);return;} if(env.DB)context.waitUntil(Promise.all([cleanupPush(env.DB),cleanupUsage(env.DB),cleanupAccounts(env.DB),cleanupDeveloperAuth(env.DB),ensureModuleThreads(env.DB),sendActivityDigests(env,env.DB),cleanupForumMedia(env)])) } }
