import { BackLink } from '../components/BackLink'
import { assetUrl } from '../hosting'
import { OPERATOR, COMMUNITY_RULES_VERSION } from './policy'
import { SUPPORT_EMAIL, SUPPORT_MAILTO } from '../support'
const reportBody='Exact URL and content/post ID / Genaue URL und Beitrags-ID:\n\nWhy I believe this content is unlawful / Warum ich den Inhalt für rechtswidrig halte:\n\nMy name and contact email / Mein Name und Kontakt-E-Mail:\n\nI believe in good faith that this notice is accurate and complete. / Ich bin nach bestem Wissen davon überzeugt, dass diese Meldung richtig und vollständig ist.'
export const CONTENT_REPORT_MAILTO=SUPPORT_MAILTO+'?subject='+encodeURIComponent('Modwerk: unlawful content / rechtswidriger Inhalt')+'&body='+encodeURIComponent(reportBody)
export function OperatorAddress(){return <address>{OPERATOR.name}<br/>{OPERATOR.street}<br/>{OPERATOR.locality}<br/>{OPERATOR.country}<br/><a href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a></address>}
export function LegalPage({route}:{route:string}){
  return <div className="community-page legal-page"><BackLink href="#library">Module library</BackLink>{route==='impressum'?<>
    <div className="page-heading"><div><p className="page-kicker">MODWERK / LEGAL</p><h1>Impressum</h1><p lang="de">Anbieterkennzeichnung und Kontakt</p></div></div>
    <section className="configuration-section" lang="de"><h2>Betreiber und Verantwortlicher</h2><OperatorAddress/><p>Modwerk wird von der oben genannten natürlichen Person betrieben.</p><h2>Kontakt</h2><p>Für Fragen zum Dienst, Datenschutzanfragen sowie als Kontaktstelle für Nutzende und Behörden: <a href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a>. Kommunikation ist auf Deutsch und Englisch möglich; Anfragen werden persönlich bearbeitet.</p><p><a href="#privacy">Datenschutzerklärung / Privacy notice</a> · <a href="#community-rules">Community-Regeln / Community rules</a> · <a href="#report-content">Rechtswidrige Inhalte melden / Report unlawful content</a></p></section>
    <section className="configuration-section"><h2>Independent community project</h2><p>Modwerk is an independent project and is not affiliated with or endorsed by Elektron. Product names identify compatible devices. Module licences and attribution remain with their respective authors.</p><a href={assetUrl('licenses/THIRD_PARTY_NOTICES.html')}>Third-party licences</a></section>
  </>:route==='report-content'?<>
    <div className="page-heading"><div><p className="page-kicker">MODWERK / COMMUNITY</p><h1>Report unlawful content</h1><p>Rechtswidrige Inhalte melden · No account required / Kein Konto erforderlich</p></div></div>
    <section className="configuration-section"><p>Send a notice to <a href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a>. Include the exact page URL and post, comment or module identifier, explain why the content is unlawful, and include your name and contact email. Confirm that you believe in good faith that the information is accurate and complete. Contact details are not required for notices about material covered by Articles 3–7 of Directive 2011/93/EU; never send or attach that material.</p><p>We acknowledge notices and communicate a decision when contact details are available. A person reviews notices without undue delay. We explain restrictions to affected contributors where permitted and tell them how to challenge a decision by replying to the contact address. Ordinary forum reports remain available for breaches of community rules.</p><p>Your notice is private. Send only the information needed to identify and assess the content. Never send passwords, firmware, recovery links or unnecessary sensitive information. See the <a href="#privacy">privacy notice</a>.</p><a className="button button-quiet" href={CONTENT_REPORT_MAILTO}>Prepare a notice in your email app</a><p className="service-note">The button opens a draft. You can also use webmail and send directly to the address above.</p></section>
    <section className="configuration-section" lang="de"><h2>Meldung per E-Mail</h2><p>Bitte senden Sie die genaue URL und Beitrags-, Kommentar- oder Modul-ID, eine Begründung der Rechtswidrigkeit, Ihren Namen und eine Kontakt-E-Mail-Adresse. Bestätigen Sie, dass Sie nach bestem Wissen von der Richtigkeit und Vollständigkeit Ihrer Meldung überzeugt sind. Für Meldungen zu Inhalten nach Artikeln 3–7 der Richtlinie 2011/93/EU sind Kontaktdaten nicht erforderlich. Senden Sie solche Inhalte niemals als Anhang.</p><p>Wenn Kontaktdaten vorliegen, bestätigen wir den Eingang und teilen die Entscheidung mit. Meldungen werden ohne unangemessene Verzögerung von einer Person geprüft. Betroffene erhalten, soweit zulässig, eine Begründung und können sich per E-Mail gegen eine Entscheidung wenden. Die Meldung bleibt vertraulich.</p></section>
  </>:<>
    <div className="page-heading"><div><p className="page-kicker">MODWERK / COMMUNITY</p><h1>Community rules</h1><p>Community-Regeln · Version {COMMUNITY_RULES_VERSION}</p></div></div>
    <section className="configuration-section"><h2>Using the community</h2><p>The community is free to use. Reading does not require an account. Posting, ratings, likes and private issue reports require a verified account. Choose a public username; keep your email and password private. We send verification and recovery emails, a welcome after signup, and activity digests you can turn off. Further news emails are optional. Usage counts are optional.</p><h2>Contributions and privacy</h2><p>Post only original or properly licensed material and preserve source attribution. Do not upload firmware, extracted stock content, credentials, personal information about others, unlawful material, harassment or spam. Never put private device logs in public discussions. Published posts, comments and configuration snapshots can be read and copied by anyone. Public contributions remain subject to their stated licence; deletion requests are assessed individually.</p><p>Module submissions and updates use GitHub pull requests and need owner review. Review does not provide automatic legal clearance. The separate module contribution requirements continue to apply.</p><h2>Moderation and decisions</h2><p>A person reviews reports and can hide content, lock a discussion or suspend an account for unlawful content or breaches of these rules. Technical limits restrict abuse and repeated requests. We do not use automated content classifiers to decide removals. Restrictions should be proportionate and take account of the context and contributors’ rights. Where contact details are available, we provide the reason, scope and available way to contest a restriction, subject to legal exceptions. Contact <a href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a> to request review by a person. <a href="#report-content">Report unlawful content</a> without an account.</p><h2>Your account and changes</h2><p>You can revoke sessions, download your account data or request removal from <a href="#account">Your account</a>. Other privacy rights can be exercised through the contact address. We explain material changes to these rules before they apply. Nothing in these rules restricts mandatory consumer or data-protection rights.</p></section>
    <section className="configuration-section" lang="de"><h2>Teilnahme und Inhalte</h2><p>Lesen ist ohne Konto möglich; die kostenlose Teilnahme setzt ein verifiziertes Konto voraus. Nutzername und Beiträge sind öffentlich, Ihre E-Mail-Adresse bleibt privat. Wir versenden Bestätigungs- und Wiederherstellungs-E-Mails, eine Willkommensnachricht nach der Registrierung und abstellbare Aktivitäts-E-Mails. Weitere News-E-Mails sind freiwillig. Nutzungszählung ist freiwillig.</p><p>Veröffentlichen Sie nur eigene oder ordnungsgemäß lizenzierte Inhalte und erhalten Sie Urheberangaben. Firmware, extrahierte Originalinhalte, Zugangsdaten, fremde personenbezogene Daten, rechtswidrige Inhalte, Belästigung und Spam sind nicht erlaubt. Private Gerätelogs gehören nicht in öffentliche Diskussionen. Öffentliche Inhalte können von Dritten kopiert werden; ihre Lizenz bleibt maßgeblich. Modulbeiträge benötigen einen GitHub-Pull-Request und die Prüfung des Betreibers.</p><h2>Moderation und Rechte</h2><p>Meldungen werden von einer Person geprüft. Inhalte können ausgeblendet, Diskussionen gesperrt und Konten bei Rechts- oder Regelverstößen suspendiert werden. Es gibt technische Missbrauchsbegrenzungen, aber keine automatischen Klassifizierer für Inhaltsentscheidungen. Einschränkungen müssen verhältnismäßig sein. Soweit rechtlich zulässig und Kontaktdaten verfügbar sind, erläutern wir Gründe und Umfang sowie den Weg zur Überprüfung. Eine persönliche Überprüfung können Sie unter <a href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a> verlangen. <a href="#report-content">Rechtswidrige Inhalte melden</a> ist ohne Konto möglich.</p><p>Unter <a href="#account">Ihr Konto</a> können Sie Sitzungen beenden, Daten herunterladen und die Löschung beantragen. Weitere Datenschutzrechte können Sie per E-Mail ausüben. Wesentliche Regeländerungen teilen wir vor ihrer Anwendung mit. Gesetzliche Verbraucher- und Datenschutzrechte bleiben unberührt.</p></section>
  </>}</div>
}
